export default {
    api:{
        getPosition:{
            url:"/position/40.10038,116.36867",
            method:"get",
            crosUrl:"/4000"
        },
        getCategories:{
            url:"/index_category",
            method:"get",
            crosUrl:"/4000"
        },
        getShops:{
            url:"/shops",
            method:"get",
            crosUrl:"/4000"
        }
    }
}