export const GETADDRRSSOBJ = "getaddressObj"
export const GETCATEGORIES = "getcategories"
export const GETSHOPS = "getshops"
export const GETUSER = "getUser"
export const RESTUSER = "restUser"
export const AUTOLOGIN = "autologin"
